export { default as Error404 } from './icons/404'
export { default as AboutIcon } from './icons/about'
export { default as ArrowIcon } from './icons/arrow'
export { default as GreetingIcon } from './icons/greeting'
export { default as StatusIcon } from './icons/statusIcon'
